export const scopes = [
  'https://mail.google.com/',
  'https://www.googleapis.com/auth/drive',
  'https://www.googleapis.com/auth/calendar',
  'openid',
  'https://www.googleapis.com/auth/userinfo.email',
  'https://www.googleapis.com/auth/userinfo.profile',
];

export const ifAppsTheme = {
  light: {
    primary: '#415E91',
    surfaceTint: '#415E91',
    onPrimary: '#FFFFFF',
    primaryContainer: '#D7E3FF',
    onPrimaryContainer: '#001B3E',
    secondary: '#565E71',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#DAE2F9',
    onSecondaryContainer: '#131C2B',
    tertiary: '#705574',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#FAD8FD',
    onTertiaryContainer: '#28132E',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#410002',
    background: '#F9F9FF',
    onBackground: '#191C20',
    surface: '#F9F9FF',
    onSurface: '#191C20',
    surfaceVariant: '#E0E2EC',
    onSurfaceVariant: '#44474E',
    outline: '#74777F',
    outlineVariant: '#C4C6D0',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#2E3036',
    inverseOnSurface: '#F0F0F7',
    inversePrimary: '#AAC7FF',
    primaryFixed: '#D7E3FF',
    onPrimaryFixed: '#001B3E',
    primaryFixedDim: '#AAC7FF',
    onPrimaryFixedVariant: '#284777',
    secondaryFixed: '#DAE2F9',
    onSecondaryFixed: '#131C2B',
    secondaryFixedDim: '#BEC6DC',
    onSecondaryFixedVariant: '#3E4759',
    tertiaryFixed: '#FAD8FD',
    onTertiaryFixed: '#28132E',
    tertiaryFixedDim: '#DDBCE0',
    onTertiaryFixedVariant: '#573E5C',
    surfaceDim: '#D9D9E0',
    surfaceBright: '#F9F9FF',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#F3F3FA',
    surfaceContainer: '#EDEDF4',
    surfaceContainerHigh: '#E7E8EE',
    surfaceContainerHighest: '#E2E2E9',
  },
  dark: {
    primary: '#AAC7FF',
    surfaceTint: '#AAC7FF',
    onPrimary: '#0B305F',
    primaryContainer: '#284777',
    onPrimaryContainer: '#D7E3FF',
    secondary: '#BEC6DC',
    onSecondary: '#283141',
    secondaryContainer: '#3E4759',
    onSecondaryContainer: '#DAE2F9',
    tertiary: '#DDBCE0',
    onTertiary: '#3F2844',
    tertiaryContainer: '#573E5C',
    onTertiaryContainer: '#FAD8FD',
    error: '#FFB4AB',
    onError: '#690005',
    errorContainer: '#93000A',
    onErrorContainer: '#FFDAD6',
    background: '#111318',
    onBackground: '#E2E2E9',
    surface: '#111318',
    onSurface: '#E2E2E9',
    surfaceVariant: '#44474E',
    onSurfaceVariant: '#C4C6D0',
    outline: '#8E9099',
    outlineVariant: '#44474E',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#E2E2E9',
    inverseOnSurface: '#2E3036',
    inversePrimary: '#415E91',
    primaryFixed: '#D7E3FF',
    onPrimaryFixed: '#001B3E',
    primaryFixedDim: '#AAC7FF',
    onPrimaryFixedVariant: '#284777',
    secondaryFixed: '#DAE2F9',
    onSecondaryFixed: '#131C2B',
    secondaryFixedDim: '#BEC6DC',
    onSecondaryFixedVariant: '#3E4759',
    tertiaryFixed: '#FAD8FD',
    onTertiaryFixed: '#28132E',
    tertiaryFixedDim: '#DDBCE0',
    onTertiaryFixedVariant: '#573E5C',
    surfaceDim: '#111318',
    surfaceBright: '#37393E',
    surfaceContainerLowest: '#0C0E13',
    surfaceContainerLow: '#191C20',
    surfaceContainer: '#1E2025',
    surfaceContainerHigh: '#282A2F',
    surfaceContainerHighest: '#33353A',
  },
};

export const drawerItem = {
  annnouncement: {
    label: 'Announcement',
    route: 'announcement',
  },
  appointment: {
    label: 'Appointment',
    route: 'appointment',
  },
  reservation: {
    label: 'Reservation',
    route: 'reservation',
  },
  room: {
    label: 'Room',
    route: 'room',
  },
  tag: {
    label: 'Tag',
    route: 'tag',
  },
  schedule: {
    label: 'My Schedule',
    route: 'schedule',
  },
  user: {
    label: 'User',
    route: 'user',
  },
  profile: {
    label: 'Profile',
    route: 'profile',
  },
  signOut: {
    label: 'Sign out',
    route: '/',
  },
};

export const dayInt = {
  MINGGU: 0,
  SENIN: 1,
  SELASA: 2,
  RABU: 3,
  KAMIS: 4,
  JUMAT: 5,
  SABTU: 6,
};

export const typeColor = {
  KELAS: '#4287f5',
  PERTEMUAN: '#5E9141',
  PINJAMRUANG: '#F542E1',
  LAINNYA: '#A4496A',
};
